### ISSUE TITLE
Enhancement: Filter by Block Type

### ISSUE THREAD

**Issue by smithjw1** [Automattic/vip-block-data-api#22]
Add the ability to filter the modules returned by passing block types as an array in the query string.

**Comment by alecgeatches** [comment]
Per @ingeniumed's work in #27, this will be available in the next release through `include` and `exclude` query parameters, as well as a server-side filter. We can close this issue once `v0.2.1` is released and merged into `trunk`.

**Comment by alecgeatches** [comment]
This is done and released with `0.2.1`! See the REST [`include` and `exclude` query parameters here](https://github.com/Automattic/vip-block-data-api#rest-api-query-parameters), along with the [`vip_block_data_api__allow_block` filter](https://github.com/Automattic/vip-block-data-api#vip_block_data_api__allow_block).
