### ISSUE TITLE
Enhancement: Write Endpoint

### ISSUE THREAD

**Issue by smithjw1** [Automattic/vip-block-data-api#24]
Allow for post creation via submission of well-formed, nested JSON.

**Comment by smithjw1** [comment]
More details from the customer:

> Yes the feature request would be to allow for POST requests (specific blocks ideally). For example, if we wanted to change a checkbox value on a few hundred image modules, we could write a quick script that iterates through and updates the values for these blocks.

**Comment by ingeniumed** [comment]
Closing this off similar to #38
