### ISSUE TITLE
WPGraphQL attributes missing with core/table array attributes

### ISSUE THREAD

**Issue by alecgeatches** [Automattic/vip-block-data-api#53]
WPGraphQL results for table attributes with array values have `Array` strings and are missing children.

## Reproduction

1. Create a post containing a table, e.g.

    ![image](https://github.com/Automattic/vip-block-data-api/assets/17870752/86e61d59-9488-4c1d-adac-881805258e0a)
    
    ```html
    <!-- wp:table -->
    <figure class="wp-block-table"><table><tbody><tr><td>Header A</td><td>Header B</td></tr><tr><td>Value 1</td><td>Value 2</td></tr></tbody></table></figure>
    <!-- /wp:table -->
    ```

2. Using the created post's ID, query for `blocks`/`innerBlocks` data:

    ```graphql
    query NewQuery {
      post(id: 431, idType: DATABASE_ID) {
        blocksData {
          blocks {
            attributes {
              name
              value
            }
            id
            name
            innerBlocks {
              attributes {
                name
                value
              }
              id
              name
              parentId
            }
          }
        }
      }
    }
    ```

3. See "Array" in results:

    ```js
    {
      "data": {
        "post": {
          "blocksData": {
            "blocks": [
              {
                "attributes": [
                  /* ... */
                  {
                    "name": "head",
                    "value": "Array"
                  },
                  {
                    "name": "body",
                    "value": "Array"
                  },
                  {
                    "name": "foot",
                    "value": "Array"
                  }
                ],
                "name": "core/table",
                "innerBlocks": null
              }
            ]
          }
        }
      }
    }
    ```

    Note that the `head`, `body`, and `foot` attributes all have a value of `"Array"`, rather than an actual array. It's not possible to reconstruct the table.

## Expected results

The REST API returns array values as expected:

```js
{
  "blocks": [
    {
      "name": "core/table",
      "attributes": {
        /* ... */
        "head": [],
        "body": [
          {
            "cells": [
              {
                "content": "Header A",
                "tag": "td"
              },
              {
                "content": "Header B",
                "tag": "td"
              }
            ]
          },
          {
            "cells": [
              {
                "content": "Value 1",
                "tag": "td"
              },
              {
                "content": "Value 2",
                "tag": "td"
              }
            ]
          }
        ],
        "foot": []
      }
    }
  ]
}
```

## Fixing it

At the time of writing, WPGraphQL `BlockAttribute` is defined as a `{ name: String, value: String }` combination:

```php
register_graphql_object_type(
    'BlockAttribute',
    [
        'description' => 'Block attribute',
        'fields'      => [
            'name'  => [
                'type'        => [ 'non_null' => 'String' ],
                'description' => 'Block data attribute name',
            ],
            'value' => [
                'type'        => [ 'non_null' => 'String' ],
                'description' => 'Block data attribute value',
            ],
        ],
    ],
);
```

Possible fixes could be to make the value support multiple types (`String|Array`) if that's possible in GraphQL, or we could continue to use the `String` type and put complex data types as JSON, e.g.

```js
"blocksData": {
  "blocks": [
    {
      "attributes": [
        /* ... */
        {
          "name": "head",
          "value": "[]"
        },
        {
          "name": "body",
          "value": "{\"cells\": [{\"content\": \"Header A\", \"tag\": \"td\"}, {\"content\": \"Header B\",\"tag\": \"td\"}]}"
        },
        {
          "name": "foot",
          "value": "[]"
        }
      ],
      "name": "core/table",
      "innerBlocks": null
    }
  ]
}
```

**Comment by james-tyner** [comment]
Just wanted to note here that we're having the same issue in our attempt to use this API at @sfstandard. It's a blocker for our use case.

**Comment by alecgeatches** [comment]
@james-tyner We'll look at getting a fix for table `"Array"` values released soon. Thanks for letting us know!

**Comment by james-tyner** [comment]
@alecgeatches great! I just want to be clear that this issue doesn't affect only tables -- it's any block with data in an array format. In our case, we're seeing issues with blocks on our homepage that come from https://github.com/alleyinteractive/wp-curate

**Comment by alecgeatches** [comment]
Thank you for the additional information, @james-tyner. If possible, could you provide the specific block you're having trouble with from [the WP Curate plugin](https://github.com/alleyinteractive/wp-curate), or even a whole reproduction like [the issue content above](https://github.com/Automattic/vip-block-data-api/issues/53#issue-2064417744)? Just want to make sure that our solution adequately covers your case. Thank you!

**Comment by alecgeatches** [comment]
I made an initial PR to solve the issue here: [Fix "Array" values in GraphQL block array data **#61**](https://github.com/Automattic/vip-block-data-api/pull/61). @james-tyner would JSON representation of array values work for your use-case? Thank you!

**Comment by james-tyner** [comment]
So fast! I'll pull in @Zamfi99 here who can take a look at the fix and our implementation
